#!/bin/sh
#
# PROVIDE: nuageinit_default_password
# REQUIRE: nuageinit_post_net
# BEFORE: SERVERS nuageinit_user_data_script
# KEYWORD: firstboot
#
# nuageinit(7) creates its default user "freebsd" with the password
# "freebsd" (hard-coded in /usr/libexec/nuageinit) whenever the user-data
# does not list users. On a cloud instance that is a known password on a
# wheel account. Once nuageinit has created and configured the users, and
# before sshd starts, this replaces that one password with "*" (matches
# nothing; the account is not locked, keys and Nova's set-password work).
# A password that user-data set - anything other than the literal
# "freebsd" - is left alone.

. /etc/rc.subr

name="nuageinit_default_password"
desc="Remove nuageinit's built-in default password"
rcvar="nuageinit_default_password_enable"
start_cmd="${name}_start"
stop_cmd=":"

: ${nuageinit_default_password_enable:="YES"}

nuageinit_default_password_start()
{
	local hash salt
	hash=$(pw usershow freebsd 2>/dev/null | cut -d: -f2)
	case "$hash" in
	'$6$'*)
		salt=${hash#\$6\$}
		salt=${salt%%\$*}
		if [ "$(openssl passwd -6 -salt "$salt" freebsd)" = "$hash" ]; then
			echo '*' | pw usermod freebsd -H 0
			echo "nuageinit_default_password: removed the built-in password of freebsd"
		fi
		;;
	esac
}

load_rc_config $name
run_rc_command "$1"
